# Custom, hand-written make targets. Not generated by devctl.
#
# `include Makefile.*.mk` globs alphabetically, so this file is parsed BEFORE
# Makefile.gen.app.mk, Makefile.gen.go.mk and Makefile.kubebuilder.mk. GNU make
# keeps the LAST recipe defined for a target, so nothing here can override those
# files. That is why the suite below is `test-integration` and not `test`.
#
# The integration tests are LOCAL ONLY. They are gated behind the `integration`
# build tag. CI runs a plain `go test ./...`, so it never compiles them.

##@ Integration tests

LOCALBIN ?= $(CURDIR)/bin

## setup-envtest is a nested module of controller-runtime and is tagged in
## lockstep with it. Keep in sync with sigs.k8s.io/controller-runtime in go.mod.
ENVTEST_VERSION ?= v0.24.1

## Kubernetes version of the envtest control plane. Track the MINOR of the
## k8s.io/* modules in go.mod (v0.36.x -> 1.36.x). Run `make envtest-list` to
## see which versions are actually published.
ENVTEST_K8S_VERSION ?= 1.36.2

ENVTEST            := $(LOCALBIN)/setup-envtest-$(ENVTEST_VERSION)
ENVTEST_ASSETS_DIR ?= $(LOCALBIN)/k8s

INTEGRATION_PKGS    ?= ./controllers/...
INTEGRATION_TIMEOUT ?= 20m
GOTESTFLAGS         ?=

$(LOCALBIN):
	mkdir -p $(LOCALBIN)

# `go install pkg@version` runs in module-agnostic mode. It does not read or
# write this repo's go.mod or go.sum, so the go-mod-tidy pre-commit hook and the
# nancy scan stay unaffected. The version-suffixed filename makes this rule
# idempotent and forces a reinstall when ENVTEST_VERSION changes.
$(ENVTEST): | $(LOCALBIN)
	@echo "====> installing setup-envtest $(ENVTEST_VERSION)"
	GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-runtime/tools/setup-envtest@$(ENVTEST_VERSION)
	mv $(LOCALBIN)/setup-envtest $(ENVTEST)

.PHONY: envtest
envtest: $(ENVTEST) ## Installs setup-envtest into ./bin (no-op when already present).
	@echo "====> $@"

.PHONY: envtest-list
envtest-list: $(ENVTEST) ## Lists the envtest control-plane versions available for this platform.
	@$(ENVTEST) list --bin-dir $(ENVTEST_ASSETS_DIR)

.PHONY: test-integration
test-integration: $(ENVTEST) ## Runs the local-only envtest integration suite (build tag: integration).
	@echo "====> $@"
	KUBEBUILDER_ASSETS="$$($(ENVTEST) use $(ENVTEST_K8S_VERSION) --bin-dir $(ENVTEST_ASSETS_DIR) -p path)" && \
	export KUBEBUILDER_ASSETS && \
	echo "KUBEBUILDER_ASSETS=$$KUBEBUILDER_ASSETS" && \
	go test -tags=integration -count=1 -timeout=$(INTEGRATION_TIMEOUT) $(GOTESTFLAGS) $(INTEGRATION_PKGS)

.PHONY: lint-integration
lint-integration: ## Lints the build-tagged integration tests, which `make lint` skips.
	@echo "====> $@"
	golangci-lint run -E gosec -E goconst --build-tags=integration --timeout=15m ./...

.PHONY: clean-envtest
clean-envtest: ## Removes the downloaded envtest assets and the setup-envtest binary.
	@echo "====> $@"
	rm -rf $(ENVTEST_ASSETS_DIR)
	rm -f $(LOCALBIN)/setup-envtest*
