version: 2.1

orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  build:
    jobs:
    - architect/go-build:
        context: architect
        name: go-build
        binary: deletion-blocker-operator
        resource_class: xlarge
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - go-build
        filters:
            # Trigger the job also on git tag.
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        context: architect
        name: push-to-app-catalog
        executor: app-build-suite
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: deletion-blocker-operator
        requires:
        - push-to-registries
        filters:
          tags:
            only: /^v.*/
          branches:
            only: /.*/ 
    - architect/push-to-app-collection:
        context: architect
        name: push-to-proxmox-app-collection
        app_name: deletion-blocker-operator
        app_collection_repo: proxmox-app-collection
        requires:
        - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-capa-app-collection
        app_name: deletion-blocker-operator
        app_collection_repo: capa-app-collection
        requires:
        - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-capz-app-collection
        app_name: deletion-blocker-operator
        app_collection_repo: capz-app-collection
        requires:
        - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-cloud-director-app-collection
        app_name: deletion-blocker-operator
        app_collection_repo: cloud-director-app-collection
        requires:
        - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-vsphere-app-collection
        app_name: deletion-blocker-operator
        app_collection_repo: vsphere-app-collection
        requires:
        - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
